stages:
  - build

docker-build:
  # Use the official docker image.
  stage: build
  script:
    - echo "$CI_DEPENDENCY_PROXY_PASSWORD" | docker login -u $CI_DEPENDENCY_PROXY_USER --password-stdin $CI_DEPENDENCY_PROXY_SERVER  
    - docker build --pull -t "$HARBOR_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_TAG" .
    - docker logout $CI_DEPENDENCY_PROXY_SERVER
    - docker login -u "$HARBOR_USER" -p "$HARBOR_PASSWORD" $HARBOR_REGISTRY
    - echo "Pushing Docker image ${HARBOR_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}"
    - docker push "$HARBOR_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_TAG"
    - docker logout $HARBOR_REGISTRY
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_TAG != null
      exists:
        - Dockerfile

